runtime: python310
entrypoint: gunicorn -b :$PORT IAFASTTRACKMODEL.wsgi:application

automatic_scaling:
  min_instances: 0          # ajusta segÃºn trÃ¡fico (p.ej., 1 para evitar cold starts)
  max_instances: 10         # establece el tope que consideres adecuado
  target_cpu_utilization: 0.65  # opcional: define cuando suele escalar


env_variables:
  PRODUCTION: "true"
  DB_USER: aifasttrackmodel
  DB_PASSWORD: Choflas_3
  DB_NAME: aifasttrackmodel
  DB_CONNECTION_NAME: iafasttrackmodel:europe-west1:aifasttrackmodel

beta_settings:
  cloud_sql_instances: iafasttrackmodel:europe-west1:aifasttrackmodel