# Generated by Django 4.2.21 on 2025-05-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='resumen_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='diagnostico_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
