# Generated by Django 4.2.21 on 2025-05-18 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_cliente_resumen_json_alter_cliente_diagnostico_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='clientes/%Y/%m/%d/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='model.cliente')),
            ],
        ),
    ]
