# Generated by Django 4.2.21 on 2025-05-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_clientefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientefile',
            name='file',
            field=models.FileField(upload_to='media/%Y/%m/%d/'),
        ),
    ]
