# Generated by Django 4.2.21 on 2025-05-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_alter_clientefile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientefile',
            name='file',
            field=models.FileField(upload_to='clientes/%Y/%m/%d/'),
        ),
    ]
