# Generated by Django 5.2.4 on 2025-08-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0005_alter_clientefile_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenAIConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=255)),
                ("model_name", models.CharField(max_length=255)),
                ("api_key", models.CharField(max_length=255)),
            ],
        ),
    ]
