# Generated by Django 5.2.4 on 2025-08-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0007_openaiconfig_api_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="openaiconfig",
            name="api_type",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
